### ISSUE TITLE
Fails to compile w/ color 0.0.7

### ISSUE THREAD

**Issue by mneilly** [BlackEdder/ggplotd#53]
The JSON files specifies ~>0.0.5 for the color package. This causes compilation to fail with color 0.0.7 as follows:

```
../../../.dub/packages/color-0.0.7/color/std/experimental/color/package.d:534:19: error: @nogc function 'std.experimental.color.colorFromStringImpl
' cannot call non-@nogc function 'std.experimental.color.colorFromStringImpl.streqi'                                                              
         if (streqi(str, k))                                                                                                                      
                   ^         
```
Modifying the JSON to ==0.0.5 allows ggplotd to compile.

**Comment by mneilly** [comment]
Sorry, realized this appears to be an issue with my installed toolchain not ggplotd.

**Comment by BlackEdder** [comment]
Last time I tried the color package didn't work on its own. That was why I pulled it into ggplotd. Does it work on its own nowadays?
