### ISSUE TITLE
Bugs after compiler update 

### ISSUE THREAD

**Issue by Sandman83** [BlackEdder/ggplotd#49]
After updating dmd from 2.079.1 to 2.080.0 ggplotd does not compiles any more. 

Example used: 
https://github.com/BlackEdder/ggplotd/issues/39#issuecomment-308050879

Compiling via dub, compilation output: 

Marvin:test519 alex$ dmd --version
DMD64 D Compiler v2.080.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
Marvin:test519 alex$ dub run
Package ggplotd can be upgraded from ~master to 1.1.4.
Use "dub upgrade" to perform those changes.
Selected package ggplotd ~master does not match the dependency specification ~>1.1.4 in package test519. Need to "dub upgrade"?
Performing "debug" build using dmd for x86_64.
derelict-util 2.1.0: building configuration "library"...
derelict-ft 1.0.2: building configuration "library"...
x11 1.0.20: building configuration "library"...
/Users/alex/.dub/packages/x11-1.0.20/x11/source/x11/extensions/XI.d(3,8): Deprecation: Symbol object.string is not visible from module XI because it is privately imported in module string
cairod 0.0.1-alpha.3+1.10.2: building configuration "static-custom-posix"...
dstats 1.0.5: building configuration "library"...
dunit 1.0.14: building configuration "library"...
gtk-d:gtkd 3.3.1: building configuration "library"...
painlesstraits 0.2.0: building configuration "library"...
ggplotd ~master: building configuration "ggplotd-gtk"...
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17): Error: constructor std.range.Zip!(double[], double[], string[], double[], double[]).Zip.this(double[] _param_0, double[] _param_1, string[] _param_2, double[] _param_3, double[] _param_4, StoppingPolicy s = cast(StoppingPolicy)0) is not callable using argument types (ZipShortest!(cast(Flag)true, double[], double[], string[], double[], double[]))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17):        cannot pass argument zip(_param_0, _param_1, _param_2, _param_3, _param_4) of type ZipShortest!(cast(Flag)true, double[], double[], string[], double[], double[]) to parameter double[] _param_0
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/axes.d(292,30): Error: template instance `ggplotd.aes.Aes!(double[], "x", double[], "y", string[], "label", double[], "angle", double[], "size").Aes.__ctor!(double[], double[], string[], double[], double[])` error instantiating
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17): Error: constructor std.range.Zip!(double[], double[], string[], double[], bool[], bool[]).Zip.this(double[] _param_0, double[] _param_1, string[] _param_2, double[] _param_3, bool[] _param_4, bool[] _param_5, StoppingPolicy s = cast(StoppingPolicy)0) is not callable using argument types (ZipShortest!(cast(Flag)true, double[], double[], string[], double[], bool[], bool[]))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17):        cannot pass argument zip(_param_0, _param_1, _param_2, _param_3, _param_4, _param_5) of type ZipShortest!(cast(Flag)true, double[], double[], string[], double[], bool[], bool[]) to parameter double[] _param_0
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/geom.d(588,60): Error: template instance `ggplotd.aes.Aes!(double[], "x", double[], "y", string[], "label", double[], "angle", bool[], "mask", bool[], "scale").Aes.__ctor!(double[], double[], string[], double[], bool[], bool[])` error instantiating
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/ggplotd.d(338,25):        instantiated from here: geomAxis!(Aes!(double[], "x", double[], "y", string[], "label", double[], "angle", double[], "size"))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17): Error: constructor std.range.Zip!(double[], double[], double[]).Zip.this(double[] _param_0, double[] _param_1, double[] _param_2, StoppingPolicy s = cast(StoppingPolicy)0) is not callable using argument types (ZipShortest!(cast(Flag)true, double[], double[], double[]))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17):        cannot pass argument zip(_param_0, _param_1, _param_2) of type ZipShortest!(cast(Flag)true, double[], double[], double[]) to parameter double[] _param_0
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/legend.d(59,9): Error: template instance `ggplotd.aes.Aes!(double[], "x", double[], "y", double[], "colour").Aes.__ctor!(double[], double[], double[])` error instantiating
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/ggplotd.d(370,53):        instantiated from here: drawContinuousLegend!(GuideStore!"colour", RGB!("rgba", double, false, cast(RGBColorSpace)0) delegate(double, double, double))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17): Error: constructor std.range.Zip!(Take!(Repeat!double), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), Take!(Repeat!double), Take!(Repeat!double), Take!(Repeat!double)).Zip.this(Take!(Repeat!double) _param_0, MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))) _param_1, MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))) _param_2, Take!(Repeat!double) _param_3, Take!(Repeat!double) _param_4, Take!(Repeat!double) _param_5, StoppingPolicy s = cast(StoppingPolicy)0) is not callable using argument types (ZipShortest!(cast(Flag)true, Take!(Repeat!double), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), Take!(Repeat!double), Take!(Repeat!double), Take!(Repeat!double)))
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/aes.d(238,17):        cannot pass argument zip(_param_0, _param_1, _param_2, _param_3, _param_4, _param_5) of type ZipShortest!(cast(Flag)true, Take!(Repeat!double), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), Take!(Repeat!double), Take!(Repeat!double), Take!(Repeat!double)) to parameter Take!(Repeat!double) _param_0
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/legend.d(99,9): Error: template instance `ggplotd.aes.Aes!(Take!(Repeat!double), "x", MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), "y", MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), "colour", Take!(Repeat!double), "width", Take!(Repeat!double), "height", Take!(Repeat!double), "fill").Aes.__ctor!(Take!(Repeat!double), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), MapResult!(__lambda1, MapResult!(__lambda2, SortedRange!(Pair[], __lambda1))), Take!(Repeat!double), Take!(Repeat!double), Take!(Repeat!double))` error instantiating
/Users/alex/.dub/packages/ggplotd-master/ggplotd/source/ggplotd/ggplotd.d(378,51):        instantiated from here: drawDiscreteLegend!(GuideStore!"colour", RGB!("rgba", double, false, cast(RGBColorSpace)0) delegate(double, double, double))
dmd failed with exit code 1.

The example compiles fine, if compiling with ldc2.

**Comment by timotheecour** [comment]
ran into same issue
